title: Jaewoo Lee
#logo: ~~~.png
description: >
  Data Analytics, Machine Learning, and Statistical Modeling Portfolio<br><br>
  Mathematics & Statistics<br>
  University of Toronto<br><br>
  SOA Exams P, FM & SRM Passed<br><br>
  Toronto, Canada<br><br>
  Python · SQL · PyTorch<br>
  scikit-learn · Tableau<br><br>
  <a href="https://www.linkedin.com/in/jaewoo-jay-lee/" target="_blank" rel="noopener noreferrer">View My LinkedIn Profile</a>
theme: jekyll-theme-minimal
